basePath: /
definitions:
  dto.SignUpUserRequest:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      topicsOfInterest:
        items:
          $ref: '#/definitions/model.TopicOfInterest'
        type: array
      username:
        type: string
    type: object
  dto.SignUpUserResponse:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
    type: object
  dto.UpdateStatisticsRequest:
    properties:
      teamId:
        example: team123
        type: string
      timeSpentOnApp:
        example: 1800000
        type: integer
      timeSpentOnTeam:
        example: 900000
        type: integer
    type: object
  dto.UpdateStatisticsResponse:
    properties:
      timeSpentOnTeams:
        items:
          $ref: '#/definitions/model.TimeSpentOnTeam'
        type: array
      totalTimeSpentOnApp:
        example: 7200000
        type: integer
      userId:
        type: string
    type: object
  entity.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      id:
        type: string
      lastname:
        type: string
      password:
        type: string
      statistics:
        $ref: '#/definitions/model.Statistics'
      teams:
        items:
          type: string
        type: array
      topicsOfInterest:
        items:
          $ref: '#/definitions/model.TopicOfInterest'
        type: array
      username:
        type: string
    type: object
  model.Statistics:
    properties:
      timeSpentOnTeams:
        items:
          $ref: '#/definitions/model.TimeSpentOnTeam'
        type: array
      totalTimeSpentOnApp:
        example: 7200000
        type: integer
    type: object
  model.TimeSpentOnTeam:
    properties:
      duration:
        example: 3600000
        type: integer
      teamId:
        type: string
    type: object
  model.TopicOfInterest:
    enum:
    - Mathematics
    - Science
    - ComputerScience
    - Programming
    - Art
    - Music
    - Photography
    - Language
    type: string
    x-enum-varnames:
    - Mathematics
    - Science
    - ComputerScience
    - Programming
    - Art
    - Music
    - Photography
    - Language
info:
  contact: {}
  title: StudyWithMe API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
      summary: Get all users
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete a user
    get:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: Get a user by ID
  /users/{id}/statistics:
    put:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      - description: The statistics update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateStatisticsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateStatisticsResponse'
      summary: Update user statistics
  /users/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: The sign-up request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SignUpUserResponse'
      summary: Register a new user
swagger: "2.0"
