basePath: /
definitions:
  dto.AddUserToTeamRequest:
    properties:
      teamId:
        type: string
      userId:
        type: string
    required:
    - teamId
    - userId
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: string
      tokenType:
        type: string
      user:
        $ref: '#/definitions/dto.UserResponse'
    type: object
  dto.SignUpUserRequest:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      password:
        type: string
      topicsOfInterest:
        items:
          $ref: '#/definitions/model.TopicOfInterest'
        type: array
      username:
        type: string
    type: object
  dto.SignUpUserResponse:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      username:
        type: string
    type: object
  dto.TeamRequest:
    properties:
      description:
        type: string
      ispublic:
        type: boolean
      name:
        type: string
    type: object
  dto.TeamResponse:
    properties:
      description:
        type: string
      ispublic:
        type: boolean
      name:
        type: string
    type: object
  dto.UpdateStatisticsRequest:
    properties:
      teamId:
        example: team123
        type: string
      timeSpentOnApp:
        example: 1800000
        type: integer
      timeSpentOnTeam:
        example: 900000
        type: integer
    type: object
  dto.UpdateStatisticsResponse:
    properties:
      timeSpentOnTeams:
        items:
          $ref: '#/definitions/model.TimeSpentOnTeam'
        type: array
      totalTimeSpentOnApp:
        example: 7200000
        type: integer
      userId:
        type: string
    type: object
  dto.UserResponse:
    properties:
      email:
        type: string
      firstname:
        type: string
      id:
        type: string
      lastname:
        type: string
      statistics:
        $ref: '#/definitions/model.Statistics'
      teams:
        items:
          type: string
        type: array
      topicsOfInterest:
        items:
          $ref: '#/definitions/model.TopicOfInterest'
        type: array
      username:
        type: string
    type: object
  entity.Team:
    properties:
      description:
        type: string
      id:
        type: string
      ispublic:
        type: boolean
      name:
        type: string
      users:
        items:
          type: string
        type: array
    type: object
  entity.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      id:
        type: string
      lastname:
        type: string
      password:
        type: string
      statistics:
        $ref: '#/definitions/model.Statistics'
      teams:
        items:
          type: string
        type: array
      topicsOfInterest:
        items:
          $ref: '#/definitions/model.TopicOfInterest'
        type: array
      username:
        type: string
    type: object
  model.Statistics:
    properties:
      timeSpentOnTeams:
        items:
          $ref: '#/definitions/model.TimeSpentOnTeam'
        type: array
      totalTimeSpentOnApp:
        example: 7200000
        type: integer
    type: object
  model.TimeSpentOnTeam:
    properties:
      duration:
        example: 3600000
        type: integer
      teamId:
        type: string
    type: object
  model.TopicOfInterest:
    enum:
    - Mathematics
    - Science
    - ComputerScience
    - Programming
    - Art
    - Music
    - Photography
    - Language
    type: string
    x-enum-varnames:
    - Mathematics
    - Science
    - ComputerScience
    - Programming
    - Art
    - Music
    - Photography
    - Language
info:
  contact: {}
  title: StudyWithMe API
  version: "1.0"
paths:
  /teams:
    get:
      description: Get a list of all teams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Team'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all teams
    post:
      consumes:
      - application/json
      description: Create a new team with the provided details
      parameters:
      - description: Team details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.TeamRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.TeamResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new team
  /teams/{id}:
    delete:
      description: Delete a team by providing team ID
      parameters:
      - description: Team ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Team deleted
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Bad Request: Missing team ID'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete a team
    get:
      description: Get team details by ID
      parameters:
      - description: Team ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Team'
        "404":
          description: Team not found
          schema:
            additionalProperties: true
            type: object
      summary: Get a team by ID
    put:
      consumes:
      - application/json
      description: Update team details by providing team ID and updated details
      parameters:
      - description: Team ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated team details
        in: body
        name: team
        required: true
        schema:
          $ref: '#/definitions/entity.Team'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Team'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update a team
  /teams/addUserToTeam:
    post:
      consumes:
      - application/json
      description: Add a user to a team by providing user ID and team ID
      parameters:
      - description: User ID and Team ID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AddUserToTeamRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User added to team
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 'Bad Request: Invalid request body or missing userId or teamId'
          schema:
            additionalProperties: true
            type: object
      summary: Add a user to a team
  /teams/by-name:
    get:
      description: Get a list of teams that match the specified name
      parameters:
      - description: Name to search for
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Team'
            type: array
        "400":
          description: 'Bad Request: Missing ''name'' query parameter'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get teams by name
  /teams/search:
    get:
      description: Get a list of X teams that start with the specified prefix
      parameters:
      - description: Prefix to search for
        in: query
        name: prefix
        required: true
        type: string
      - description: Number of teams to retrieve
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Team'
            type: array
        "400":
          description: 'Bad Request: Missing prefix or limit query parameters, or
            limit is NaN'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get X teams by prefix
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all users
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a user
    get:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID
    put:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a user
  /users/{id}/statistics:
    put:
      consumes:
      - application/json
      parameters:
      - description: The user's ID
        in: path
        name: id
        required: true
        type: string
      - description: The statistics update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateStatisticsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateStatisticsResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update user statistics
  /users/login:
    post:
      consumes:
      - application/json
      description: Accepts either `email` or `username` along with `password`. Returns
        an access token and the full user (without password).
      parameters:
      - description: The login request (email or username + password)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user by email or username and return JWT
  /users/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: The sign-up request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SignUpUserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
  /voice/{teamId}:
    get:
      parameters:
      - description: Team ID
        in: path
        name: teamId
        required: true
        type: string
      - description: User ID
        in: query
        name: userId
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols - WebSocket connection established
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Room is full
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Join voice chat room
  /voice/{teamId}/leave:
    delete:
      parameters:
      - description: Team ID
        in: path
        name: teamId
        required: true
        type: string
      - description: User ID
        in: query
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: Successfully left room
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Room not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Leave voice chat room
swagger: "2.0"
