name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Compile and run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
        cache: true

    - name: Compile and run tests
      run: go test -v ./...

  check-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Check if the code is formatted
        run: |
          GOFMT_OUTPUT=$(go fmt ./...)
          if [ -n "$GOFMT_OUTPUT" ]; then
            echo "::error::The following files are not correctly formatted:"
            echo "$GOFMT_OUTPUT"
            echo ""
            echo "Please run 'go fmt ./...' locally and commit the changes."
            exit 1
          fi

  check-swagger:
    name: Check Swagger comments and files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Check Swagger comments and generated files
        run: |
          # Run Swagger tools
          swag fmt -g main.go
          swag init -g main.go

          # Check if any files changed
          if ! git diff --exit-code; then
            echo "::error::Swagger comment formatting and/or generated files are out of date."
            echo "Please run 'swag fmt -g main.go' and 'swag init -g main.go' locally and commit the changes."
            exit 1
          fi
